=== kbase/cdm-data-loaders/tests/data/uniprot/uniref/uniref.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- *****************************************************************************
    UniProt Reference Clusters(UniRef) 
        Version:        version 3.1
        Date:           21-Jun-2011

    Copyright (c) 2011 UniProt consortium 
    All rights reserved.
*******************************************************************************-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://uniprot.org/uniref" targetNamespace="http://uniprot.org/uniref" elementFormDefault="qualified">
    <xs:complexType name="propertyType">
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="dbReferenceType">
        <xs:annotation>
            <xs:documentation>Database cross-references</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>The name of the database this cross-reference is referring to.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="id" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>The ID referred to.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="memberType">
        <xs:annotation>
            <xs:documentation>UniRef50/90/100 cluster members</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="dbReference" type="dbReferenceType"/>
            <xs:element name="sequence" minOccurs="0">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="length" type="xs:int" use="required"/>
                            <xs:attribute name="checksum" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="entryType">
        <xs:annotation>
            <xs:documentation>UniRef50/90/100 entry</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="representativeMember" type="memberType"/>
            <xs:element name="member" type="memberType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required">
            <xs:annotation>
                <xs:documentation>The entry identifier.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="updated" type="xs:date" use="required">
            <xs:annotation>
                <xs:documentation>The update date for the entry.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="UniRef100">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entry" type="entryType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="releaseDate" type="xs:date" use="required"/>
            <xs:attribute name="version" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="UniRef90">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entry" type="entryType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="releaseDate" type="xs:date" use="required"/>
            <xs:attribute name="version" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="UniRef50">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entry" type="entryType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="releaseDate" type="xs:date" use="required"/>
            <xs:attribute name="version" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="UniRef">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entry" type="entryType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="releaseDate" type="xs:date" use="optional"/>
            <xs:attribute name="version" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="UniRefType">
        <xs:choice>
            <xs:element ref="UniRef100"/>
            <xs:element ref="UniRef90"/>
            <xs:element ref="UniRef50"/>
            <xs:element ref="UniRef"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== kbase/cdm-data-loaders/tests/data/uniprot/uniref/integration/uniref_chunk_00001.xml
<?xml version="1.0" encoding="UTF-8"?>
<UniRef50 xmlns="http://uniprot.org/uniref"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://uniprot.org/uniref http://www.uniprot.org/support/docs/uniref.xsd"
 releaseDate="2025-02-05" version="2025_01">
    <entry id="UniRef50_A0AB34IYJ6" updated="2025-02-05">
        <name>Cluster: PKZILLA-1 giant polyketide synthase</name>
        <property type="member count" value="1"/>
        <property type="common taxon" value="Prymnesium parvum"/>
        <property type="common taxon ID" value="97485"/>
        <property type="GO Molecular Function" value="GO:0004315"/>
        <representativeMember>
            <dbReference type="UniProtKB ID" id="A0AB34IYJ6_PRYPA">
                <property type="UniProtKB accession" value="A0AB34IYJ6"/>
                <property type="UniParc ID" value="UPI003596FD28"/>
                <property type="UniRef100 ID" value="UniRef100_A0AB34IYJ6"/>
                <property type="UniRef90 ID" value="UniRef90_A0AB34IYJ6"/>
                <property type="protein name" value="PKZILLA-1 giant polyketide synthase"/>
                <property type="source organism" value="Prymnesium parvum (Golden alga)"/>
                <property type="NCBI taxonomy" value="97485"/>
                <property type="length" value="45212"/>
                <property type="isSeed" value="true"/>
            </dbReference>
            <sequence length="45212" checksum="385E596EB33D030E">SNIP</sequence>
        </representativeMember>
    </entry>
    <entry id="UniRef50_A0A410P257" updated="2024-07-24">
        <name>Cluster: Glycogen synthase</name>
        <property type="member count" value="2"/>
        <property type="common taxon" value="Velamenicoccus archaeovorus"/>
        <property type="common taxon ID" value="1930593"/>
        <representativeMember>
            <dbReference type="UniProtKB ID" id="A0A410P257_VELA1">
                <property type="UniProtKB accession" value="A0A410P257"/>
                <property type="UniParc ID" value="UPI000FFCD83E"/>
                <property type="UniRef100 ID" value="UniRef100_A0A410P257"/>
                <property type="UniRef90 ID" value="UniRef90_A0A410P257"/>
                <property type="protein name" value="Glycogen synthase"/>
                <property type="source organism" value="Velamenicoccus archaeovorus"/>
                <property type="NCBI taxonomy" value="1930593"/>
                <property type="length" value="39677"/>
            </dbReference>
            <sequence length="39677" checksum="976AC558673E4C32">SNIP</sequence>
        </representativeMember>
        <member>
            <dbReference type="UniParc ID" id="UPI000FFEDAD7">
                <property type="UniRef100 ID" value="UniRef100_UPI000FFEDAD7"/>
                <property type="UniRef90 ID" value="UniRef90_A0A410P257"/>
                <property type="protein name" value="UPF0489 family protein"/>
                <property type="source organism" value="Candidatus Velamenicoccus archaeovorus"/>
                <property type="NCBI taxonomy" value="1930593"/>
                <property type="length" value="39686"/>
                <property type="isSeed" value="true"/>
            </dbReference>
        </member>
    </entry>
    <entry id="UniRef50_UPI00358F51CD" updated="2024-11-27">
        <name>Cluster: LOW QUALITY PROTEIN: titin</name>
        <property type="member count" value="1"/>
        <property type="common taxon" value="Myxine glutinosa"/>
        <property type="common taxon ID" value="7769"/>
        <representativeMember>
            <dbReference type="UniParc ID" id="UPI00358F51CD">
                <property type="UniRef100 ID" value="UniRef100_UPI00358F51CD"/>
                <property type="UniRef90 ID" value="UniRef90_UPI00358F51CD"/>
                <property type="protein name" value="LOW QUALITY PROTEIN: titin"/>
                <property type="source organism" value="Myxine glutinosa"/>
                <property type="NCBI taxonomy" value="7769"/>
                <property type="length" value="47063"/>
                <property type="isSeed" value="true"/>
            </dbReference>
            <sequence length="47063" checksum="48729625616C010E">SNIP</sequence>
        </representativeMember>
    </entry>
</UniRef50>
